name: Push to GitHub pages on merge

on:
  push:
    branches:
      - master

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: node & npm init 
        run: npm ci
          
      - name: test & linter
        run: |
          CI=true npm run test
          npm run lint

      - name: build
        run: npm run build
        
      - name: deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
          