name: Build and Test Tinder 4 Movies App

on: [push]

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: node & npm init 
        run: npm ci
      - name: test & linter
        run: |
          CI=true npm run test
          npm run lint
      - name: build & deploy to GitHub Pages
        run: npm run deploy
          